### ISSUE TITLE
Publish a post or report on LinkedIn promoting GraphQL EU

### ISSUE THREAD

**Issue by Urigo** [graphql/marketing#19]
### Is there an existing issue for this?

- [X] I have searched existing issues

### If this suggestion is on behalf of another committee, which one?

None

### Provide a detailed description of your suggestion for improvement(s).

Here is an example: 
https://www.linkedin.com/posts/karolinamerda_graphql-unconference-graphqleu-activity-7075083651763355649-xmvp?utm_source=share&utm_medium=member_desktop

**Comment by doc-jones** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7076906643472408576

**Comment by Urigo** [comment]
Thank you @doc-jones 
Could you edit the post in order to add a link to the Meetup event also to the post?
Currently it is only an image
The link to the event is https://www.meetup.com/graphql-gathering-eu/events/294044013/
