### ISSUE TITLE
[BUG] README urls for folders in repo returns a 404

### ISSUE THREAD

**Issue by meenakshi-dhanani** [graphql/marketing#2]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Contact Details

meena24dhanani@gmail.com

### For which project are you reporting this bug?

None

### Bug Description

The README includes links to /assets and /plans folders in the repository. Both of those links return a 404.

![plans-marketing](https://user-images.githubusercontent.com/14279061/230865611-75186886-7030-4e1e-a062-580273b795d7.gif)

**Comment by meenakshi-dhanani** [comment]
#3 - Link to PR

**Comment by doc-jones** [comment]
Love the animated gif 😍
