### ISSUE TITLE
Publish a post or report on LinkedIn promoting GraphQL Amsterdam Meetup

### ISSUE THREAD

**Issue by Urigo** [graphql/marketing#20]
### Is there an existing issue for this?

- [X] I have searched existing issues

### If this suggestion is on behalf of another committee, which one?

None

### Provide a detailed description of your suggestion for improvement(s).

https://www.linkedin.com/posts/urigo_graphql-meetup-with-bookingcom-and-albert-activity-7076878619473526784-p_3u?utm_source=share&utm_medium=member_desktop

**Comment by doc-jones** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7076904916023156737
