### ISSUE TITLE
Publish a post or report on LinkedIn promoting GraphQL Zurich Meetup

### ISSUE THREAD

**Issue by Urigo** [graphql/marketing#21]
### Is there an existing issue for this?

- [X] I have searched existing issues

### If this suggestion is on behalf of another committee, which one?

None

### Provide a detailed description of your suggestion for improvement(s).

https://www.linkedin.com/posts/graphql-zurich_zurich-activity-7075421283710070784-StpA?utm_source=share&utm_medium=member_desktop

**Comment by doc-jones** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7076904325377085440
